初稿
ikcamp/tech-translation pull request #15
Opened 2017-06-21 03:21 UTC by Gary9800

2017-06-21 06:38 UTC, blueken requested changes

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> + # 翻译 | 内存管理速成课（1）
翻译 | 内存管理速成课（1）
-》
内存管理速成课 - 第一部（共三部）
老司机带你秒懂内存管理 - 第一部（共三部）

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +当你在使用JavaScript时，实际上并不需要考虑内存。它被抽象出来，你不会直接接触到内存。
1.“它被抽象出来” , 这里的 “它” 需要进一步明确是 “内存”
2. 这里的abstrat不是抽象，而是抽离。

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +JS引擎充当中介。它为您管理内存。
1. instead 在这里可译为， 取而代之的是。 
2. 中间的句号，不用和原文一致，中间改为逗号

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +让我们假设一些JS代码，创建一个变量。
1. let's say 是比如说、举例来说的意思
2. 原文有提到React, 考虑到下面的图中有 React的图标，所以React 字眼不能丢

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +它将在内存中找到可以容纳该二进制的空间。这个过程称为分配内存。
中间用逗号

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +然后，引擎将跟踪该变量是否仍然可以从程序中的任何地方访问。如果该变量无法再访问，则内存将被回收，以便JS引擎可以在其中添加新值。
“在其中” 有一定程度的歧义
可译为

以便js引擎可以在回收的内存中存放新的值

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +这种在内存中监控变量--字符串、对象或其他类型--并释放掉不再使用的变量所占用的内存的过程，成为垃圾回收。
1。 -- -- 替换为小括号
2. “成为”  -> "我们称之为”

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +这种自动内存管理可以使开发人员更轻松。但它也增加了一些开销。而这种开销有时会使性能不可预测。
第二个句号应该换成逗号

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +手动管理内存的语言不同。例如，我们来看看React如何使用C写入内存（现在可以通过[WebAssembly](https://hacks.mozilla.org/2017/02/a-cartoon-intro-to-webassembly/)来[实现](https://www.youtube.com/watch?v=3GHJ4cbxsVQ)）。
“手动管理内存的语言不同”  这句太过简短，有些突兀。
考虑换成
“手动管理内存的语言不太一样” 
或者
“和自动管理内存的语言相比，需要手动管理内存的语言有些不同”

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +C没有JavaScript在内存上的抽象层。而是直接在内存上运行。你可以从内存加载东西，也可以将内容存储到内存中。
C后面加上“语言”两个字 ，下面的也一样

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +这并不意味着你完全要自己处理。即使在手动内存管理的语言中，通常会从语言运行时获得一些帮助。例如，在C中，运行时将跟踪哪些内存地址在 "空闲列表" 中打开。
运行时将跟踪哪些内存地址在 "空闲列表" 中打开

->

运行时会把哪些内存地址可用记录在一张表中，这张表叫做空闲列表

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +你必须弄清楚何时调用这些功能。这就是为什么它被称为手动内存管理——你自己管理内存。
1. 调用这些功能。 ‘这些’是什么？ 需要明确
2. 你自己管理内存 -》 你得自己管理内存

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +这就是为什么许多现代语言使用自动内存管理的原因——以避免人为错误。但这是以性能为代价的。 我将在下一篇文章中更多地解释这一点。
“以避免人为错误”  ，语病。 去掉“以”字

2017-06-21 06:38 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +要理解为什么将ArrayBuffer和SharedArrayBuffer添加到JavaScript中，您需要了解一些关于内存管理的内容。
所有的英文和中文字之都要前后留空格
将ArrayBuffer和 -》 将 ArrayBuffer 和

请检查全文

2017-06-22 03:06 UTC, Gary9800 commented on TODO/a-crash-course-in-memory-management.md
> +当你在使用JavaScript时，实际上并不需要考虑内存。它被抽象出来，你不会直接接触到内存。
当你在使用 JavaScript 时，实际上并不需要考虑内存。内存被抽象出来，你不会直接接触到它。

2017-06-22 03:06 UTC, Gary9800 commented on TODO/a-crash-course-in-memory-management.md
> +JS引擎充当中介。它为您管理内存。
取而代之的是 JS 引擎充当中介，为您管理内存。

2017-06-22 03:20 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +您可以将机器中的内存看作一堆盒子。就像你在办公室里的邮箱，或是要求小孩子们使用的收纳箱。
要求小孩子们使用的收纳箱。 -》 “要求”两个字原文貌似没有体现，可以删除

2017-06-22 03:35 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
> +和自动管理内存的语言相比，需要手动管理内存的语言有些不同。例如，我们来看看 React 如何使用 C 语言写入内存（现在可以通过[WebAssembly](https://hacks.mozilla.org/2017/02/a-cartoon-intro-to-webassembly/)来[实现](https://www.youtube.com/watch?v=3GHJ4cbxsVQ)）。
现在可以通过 WebAssembly  -》 
后面加 "实现“

2017-06-22 03:35 UTC, blueken commented on TODO/a-crash-course-in-memory-management.md
>  作为一名开发人员，弄清楚何时清除不同部分的内存可能很难。如果您在错误的时间进行操作，可能会出现bug，甚至导致安全漏洞。如果你不这样做，你的内存就会耗尽。
全局统一对读者的称呼，  您 或者 你。 不要混用

2017-06-22 05:11 UTC, merged